import { useState } from "react";
import { FlaskConical, Car, Factory, Ban, RotateCcw } from "lucide-react";
import { api } from "../api/client";
import type { NetNode, Operations } from "../api/types";
export function ScenarioStudio({nodes,origin,destination,start,ops,onChange}:{nodes:NetNode[];origin:string;destination:string;start:string;ops:Operations|null;onChange:()=>Promise<void>}){
 const [node,setNode]=useState("HN");const [busy,setBusy]=useState(false);const [err,setErr]=useState("");
 async function apply(kind:string){setBusy(true);setErr("");try{await api.addEvent({kind,node:kind==="traffic"?undefined:node,origin:kind==="traffic"?origin:undefined,destination:kind==="traffic"?destination:undefined,start,end:new Date(Date.parse(start)+7*86400000).toISOString(),minutes:kind==="traffic"?180:90,reason:kind==="traffic"?"Heavy traffic on selected direct corridor":kind==="closure"?"Political / operational closure at selected facility":"Hub congestion: loading capacity reduced"});await onChange()}catch(e){setErr(String(e))}finally{setBusy(false)}}
 async function resolve(id:string){setBusy(true);try{await api.resolveEvent(id);await onChange()}catch(e){setErr(String(e))}finally{setBusy(false)}}
 return <section className="studio"><div className="studio-title"><span><FlaskConical size={16}/> Scenario Studio</span><span className="mini mini--est">SIMULATION</span></div><p>Change a condition. See your arrival promise adapt.</p><div className="studio-controls"><label>Target facility<select aria-label="Scenario target facility" value={node} onChange={e=>setNode(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><button disabled={busy} onClick={()=>apply("traffic")}><Car size={18}/><span>Heavy traffic<small>+3h · direct corridor</small></span></button><button disabled={busy} onClick={()=>apply("hub_delay")}><Factory size={18}/><span>Hub congestion<small>+90m · selected hub</small></span></button><button disabled={busy} onClick={()=>apply("closure")}><Ban size={18}/><span>Political closure<small>Avoid selected hub · 7 days</small></span></button></div>{err&&<div role="alert" className="notice notice--warn">{err}</div>}{ops?.events.map(e=><div className="scenario-event" key={e.id}><span>{e.reason} <small>· {new Date(e.end).toLocaleDateString()}</small></span><button aria-label={`Resolve ${e.reason}`} disabled={busy} onClick={()=>resolve(e.id)}><RotateCcw size={13}/> Resolve</button></div>)}</section>
}
