/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Health */
    get: operations["get_health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get State */
    get: operations["get_state_api_state_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/network": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Network */
    get: operations["get_network_api_network_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/data-summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Data Summary */
    get: operations["get_data_summary_api_data_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/routes/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Search */
    post: operations["post_search_api_routes_search_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lanes/{lane_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Lane */
    patch: operations["patch_lane_api_lanes__lane_id__patch"];
    trace?: never;
  };
  "/api/nodes/{node_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Node */
    patch: operations["patch_node_api_nodes__node_id__patch"];
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Events */
    get: operations["get_events_api_events_get"];
    put?: never;
    /** Post Event */
    post: operations["post_event_api_events_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Event Revision */
    post: operations["post_event_revision_api_events__event_id__revisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Plans */
    get: operations["get_plans_api_plans_get"];
    put?: never;
    /** Post Plan */
    post: operations["post_plan_api_plans_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plans/{plan_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Plan View */
    get: operations["get_plan_view_api_plans__plan_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plans/{plan_id}/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Decisions */
    get: operations["get_decisions_api_plans__plan_id__decisions_get"];
    put?: never;
    /** Post Decision */
    post: operations["post_decision_api_plans__plan_id__decisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/demo/presets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Preset */
    post: operations["post_preset_api_demo_presets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/demo/clock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Clock */
    post: operations["post_clock_api_demo_clock_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/demo/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Reset */
    post: operations["post_reset_api_demo_reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/map/geometry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Map Geometry */
    get: operations["get_map_geometry_api_map_geometry_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Integrations */
    get: operations["get_integrations_api_integrations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations/observations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Observations */
    get: operations["get_observations_api_integrations_observations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Integrations Refresh */
    post: operations["post_integrations_refresh_api_integrations_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Api 404 Catchall */
    get: operations["api_404_catchall_api__path__put"];
    /** Api 404 Catchall */
    put: operations["api_404_catchall_api__path__put"];
    /** Api 404 Catchall */
    post: operations["api_404_catchall_api__path__put"];
    /** Api 404 Catchall */
    delete: operations["api_404_catchall_api__path__put"];
    options?: never;
    head?: never;
    /** Api 404 Catchall */
    patch: operations["api_404_catchall_api__path__put"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdvanceClock */
    AdvanceClock: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /** Target Clock */
      target_clock: string;
    };
    /** ApplyPreset */
    ApplyPreset: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /**
       * Preset Id
       * @enum {string}
       */
      preset_id: "traffic_direct" | "handling_munich" | "closure_strasbourg";
    };
    /** CalendarRule */
    CalendarRule: {
      /** Id */
      id: string;
      /** Lane Id */
      lane_id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "road" | "air";
      /** Timezone */
      timezone: string;
      /** Weekday */
      weekday: number;
      /** Start Local Time */
      start_local_time: string;
      /** End Next Day Local Time */
      end_next_day_local_time: string;
      /**
       * Action
       * @constant
       */
      action: "pause_travel";
      /** Provenance */
      provenance: string;
    };
    /** CapacityExample */
    CapacityExample: {
      /** Source File */
      source_file: string;
      /** Relation */
      relation: string;
      /** Destination */
      destination: string;
      /** Date */
      date: string;
      /** Planned Trailers */
      planned_trailers: number;
      /** Needed Trailers */
      needed_trailers: number;
      /** Special Trips */
      special_trips: number;
      /** Loading Metres */
      loading_metres: number;
      /** Trailer Capacity Metres */
      trailer_capacity_metres: number;
    };
    /** CreateEvent */
    CreateEvent: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      event: components["schemas"]["EventInput"];
    };
    /** CreatePlan */
    CreatePlan: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /** Search Id */
      search_id: string;
      /** Route Id */
      route_id: string;
      /** Name */
      name: string;
    };
    /** DataSummary */
    DataSummary: {
      /** Sources */
      sources?: components["schemas"]["SourceSummary"][];
      /** Assumptions */
      assumptions?: string[];
      /** Import Complete */
      import_complete: boolean;
      capacity_example?: components["schemas"]["CapacityExample"] | null;
    };
    /** Decision */
    Decision: {
      /** Id */
      id: string;
      /** Plan Id */
      plan_id: string;
      /** Actor */
      actor: string;
      /**
       * Action
       * @enum {string}
       */
      action: "accept_route" | "keep_selected" | "defer";
      /** Reason */
      reason: string;
      /** Selected Route Id */
      selected_route_id?: string | null;
      /** Superseded Route Id */
      superseded_route_id?: string | null;
      /** Decided At */
      decided_at: string;
      review_evidence: components["schemas"]["ReviewEvidence"];
    };
    /** DecisionList */
    DecisionList: {
      /** Plan Id */
      plan_id: string;
      /** Decisions */
      decisions?: components["schemas"]["Decision"][];
    };
    /** DecisionRequest */
    DecisionRequest: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /** Expected Plan Revision */
      expected_plan_revision: number;
      /** Actor */
      actor: string;
      /**
       * Action
       * @enum {string}
       */
      action: "accept_route" | "keep_selected" | "defer";
      /** Route Id */
      route_id?: string | null;
      /** Reason */
      reason: string;
    };
    /** DecisionResult */
    DecisionResult: {
      plan: components["schemas"]["PlanView"];
      decision: components["schemas"]["Decision"];
      /** Mutation Id */
      mutation_id: string;
    };
    /** DepartureRule */
    DepartureRule: {
      /** Id */
      id: string;
      /** Weekdays */
      weekdays: number[];
      /** Local Time */
      local_time: string;
      /** Cutoff Minutes */
      cutoff_minutes: number;
    };
    /** Diagnostic */
    Diagnostic: {
      /**
       * Category
       * @enum {string}
       */
      category:
        | "connectivity"
        | "closure"
        | "calendar"
        | "cutoff"
        | "profile"
        | "limit";
      /**
       * Code
       * @enum {string}
       */
      code:
        | "CLOSED_LANE"
        | "CANCELLED_DEPARTURE"
        | "INACTIVE_LANE"
        | "OUTSIDE_VALIDITY"
        | "HORIZON_EXCEEDED"
        | "DISCONNECTED"
        | "MISSED_CUTOFF"
        | "PROFILE_REJECTED"
        | "SEARCH_LIMIT";
      /** Message */
      message: string;
      /** Target Id */
      target_id?: string | null;
    };
    /** Event */
    Event: {
      /**
       * Type
       * @enum {string}
       */
      type: "traffic" | "weather" | "political" | "operational";
      /**
       * Source Kind
       * @enum {string}
       */
      source_kind: "manager" | "demo_feed" | "provider";
      /** External Id */
      external_id: string;
      /** Source Reference */
      source_reference: string;
      /** Observed At */
      observed_at: string;
      /** Valid From */
      valid_from: string;
      /** Valid Until */
      valid_until?: string | null;
      /** Review Due At */
      review_due_at?: string | null;
      /**
       * Target Kind
       * @enum {string}
       */
      target_kind: "node" | "lane";
      /** Target Id */
      target_id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "road" | "air";
      /**
       * Effect Type
       * @enum {string}
       */
      effect_type:
        | "additional_travel_minutes"
        | "additional_handling_minutes"
        | "closure"
        | "departure_cancellation";
      /** Effect Minutes */
      effect_minutes?: number | null;
      /**
       * Verification Status
       * @enum {string}
       */
      verification_status: "pending" | "accepted";
      /**
       * Lifecycle Status
       * @enum {string}
       */
      lifecycle_status: "active" | "withdrawn";
      /** Correlation Key */
      correlation_key: string;
      /** Reason */
      reason: string;
      /** Applies To Departure At */
      applies_to_departure_at?: string | null;
      /** Observation Id */
      observation_id?: string | null;
      /** Id */
      id: string;
      /** Version */
      version: number;
      /** Reported By */
      reported_by: string;
      /** Received At */
      received_at: string;
      /** Review Overdue */
      review_overdue: boolean;
    };
    /** EventInput */
    EventInput: {
      /**
       * Type
       * @enum {string}
       */
      type: "traffic" | "weather" | "political" | "operational";
      /**
       * Source Kind
       * @enum {string}
       */
      source_kind: "manager" | "demo_feed" | "provider";
      /** External Id */
      external_id: string;
      /** Source Reference */
      source_reference: string;
      /** Observed At */
      observed_at: string;
      /** Valid From */
      valid_from: string;
      /** Valid Until */
      valid_until?: string | null;
      /** Review Due At */
      review_due_at?: string | null;
      /**
       * Target Kind
       * @enum {string}
       */
      target_kind: "node" | "lane";
      /** Target Id */
      target_id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "road" | "air";
      /**
       * Effect Type
       * @enum {string}
       */
      effect_type:
        | "additional_travel_minutes"
        | "additional_handling_minutes"
        | "closure"
        | "departure_cancellation";
      /** Effect Minutes */
      effect_minutes?: number | null;
      /**
       * Verification Status
       * @enum {string}
       */
      verification_status: "pending" | "accepted";
      /**
       * Lifecycle Status
       * @enum {string}
       */
      lifecycle_status: "active" | "withdrawn";
      /** Correlation Key */
      correlation_key: string;
      /** Reason */
      reason: string;
      /** Applies To Departure At */
      applies_to_departure_at?: string | null;
      /** Observation Id */
      observation_id?: string | null;
    };
    /** EventList */
    EventList: {
      snapshot: components["schemas"]["Snapshot"];
      /** Events */
      events: components["schemas"]["Event"][];
    };
    /** EventMutationResult */
    EventMutationResult: {
      snapshot: components["schemas"]["Snapshot"];
      event: components["schemas"]["Event"];
      /** Mutation Id */
      mutation_id: string;
    };
    /** Geometry */
    Geometry: {
      /**
       * Type
       * @constant
       */
      type: "LineString";
      /** Coordinates */
      coordinates: number[][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded" | "unhealthy";
      /**
       * Database
       * @enum {string}
       */
      database: "connected" | "error";
      /** Simulation Clock */
      simulation_clock: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "demo" | "live";
      /** Dataset Id */
      dataset_id: string;
    };
    /** Integrations */
    Integrations: {
      snapshot: components["schemas"]["Snapshot"];
      /** Integrations Revision */
      integrations_revision: number;
      /** Providers */
      providers?: components["schemas"]["ProviderStatus"][];
    };
    /** Lane */
    Lane: {
      /** Id */
      id: string;
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "road" | "air";
      /** Duration Minutes */
      duration_minutes: number;
      /** Active */
      active: boolean;
      /** Valid From */
      valid_from: string;
      /** Valid To */
      valid_to: string;
      /** Departures */
      departures?: components["schemas"]["DepartureRule"][];
      /** Provenance */
      provenance: string;
    };
    /** LaneGeometry */
    LaneGeometry: {
      /** Lane Id */
      lane_id: string;
      /** Departure At */
      departure_at?: string | null;
      /**
       * Geometry Kind
       * @enum {string}
       */
      geometry_kind: "schematic" | "provider_road";
      geometry: components["schemas"]["Geometry"];
      /** Source */
      source: string;
      /** Attribution */
      attribution: string;
      /** Fetched At */
      fetched_at?: string | null;
      /** Stale */
      stale: boolean;
    };
    /** LaneMutationResult */
    LaneMutationResult: {
      snapshot: components["schemas"]["Snapshot"];
      lane: components["schemas"]["Lane"];
      /** Mutation Id */
      mutation_id: string;
    };
    /** LaneUpdate */
    LaneUpdate: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /** Active */
      active?: boolean | null;
      /** Duration Minutes */
      duration_minutes?: number | null;
      /** Departures */
      departures?: components["schemas"]["DepartureRule"][] | null;
    };
    /** MapGeometry */
    MapGeometry: {
      snapshot: components["schemas"]["Snapshot"];
      /** Integrations Revision */
      integrations_revision: number;
      /** Lanes */
      lanes?: components["schemas"]["LaneGeometry"][];
    };
    /** Network */
    Network: {
      snapshot: components["schemas"]["Snapshot"];
      /** Nodes */
      nodes: components["schemas"]["Node"][];
      /** Lanes */
      lanes: components["schemas"]["Lane"][];
      /** Calendar Rules */
      calendar_rules: components["schemas"]["CalendarRule"][];
      /** Service Profiles */
      service_profiles: components["schemas"]["ServiceProfile"][];
    };
    /** Node */
    Node: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Type
       * @enum {string}
       */
      type: "hub" | "branch" | "hand_over";
      /** Country */
      country: string;
      /** Timezone */
      timezone: string;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
      /** Processing Minutes */
      processing_minutes: number;
      /** Active */
      active: boolean;
      /** Provenance */
      provenance: string;
    };
    /** NodeMutationResult */
    NodeMutationResult: {
      snapshot: components["schemas"]["Snapshot"];
      node: components["schemas"]["Node"];
      /** Mutation Id */
      mutation_id: string;
    };
    /** NodeUpdate */
    NodeUpdate: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /** Active */
      active?: boolean | null;
      /** Processing Minutes */
      processing_minutes?: number | null;
    };
    /** Observation */
    Observation: {
      /** Id */
      id: string;
      /**
       * Provider
       * @enum {string}
       */
      provider: "open_meteo" | "tomtom" | "operator_bulletins";
      /**
       * Target Kind
       * @enum {string}
       */
      target_kind: "node" | "lane";
      /** Target Id */
      target_id: string;
      /** Intended Departure At */
      intended_departure_at?: string | null;
      /** Observed At */
      observed_at: string;
      /** Fetched At */
      fetched_at: string;
      /** Valid From */
      valid_from: string;
      /** Valid Until */
      valid_until?: string | null;
      /** Metrics */
      metrics?: {
        [key: string]: unknown;
      };
      /** Raw Digest */
      raw_digest: string;
      /** Attribution */
      attribution: string;
      /** Stale */
      stale: boolean;
    };
    /** ObservationList */
    ObservationList: {
      snapshot: components["schemas"]["Snapshot"];
      /** Integrations Revision */
      integrations_revision: number;
      /** Observations */
      observations?: components["schemas"]["Observation"][];
    };
    /** OriginProgress */
    OriginProgress: {
      /** Plan Id */
      plan_id: string;
      /** Recorded At */
      recorded_at: string;
      /** Frozen Segments */
      frozen_segments?: components["schemas"]["Segment"][];
      /** Completed Work Minutes */
      completed_work_minutes: number;
      /** Handling Complete */
      handling_complete: boolean;
      /**
       * First Mode
       * @enum {string}
       */
      first_mode: "road" | "air";
    };
    /** PlanList */
    PlanList: {
      snapshot: components["schemas"]["Snapshot"];
      /** Plans Revision */
      plans_revision: number;
      /** Plans */
      plans?: components["schemas"]["PlanView"][];
    };
    /** PlanView */
    PlanView: {
      /** Plan Id */
      plan_id: string;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: "stable" | "review_required" | "blocked" | "outside_demo_scope";
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      request: components["schemas"]["SearchRequest"];
      selected_itinerary: components["schemas"]["Route"];
      selected_projection?: components["schemas"]["Route"] | null;
      /** Alternative Recommendations */
      alternative_recommendations?: components["schemas"]["Route"][];
      /**
       * Decisions Count
       * @default 0
       */
      decisions_count: number;
      latest_decision?: components["schemas"]["Decision"] | null;
      /**
       * Plan Revision
       * @default 0
       */
      plan_revision: number;
      /** Review Reasons */
      review_reasons?: string[];
      origin_progress?: components["schemas"]["OriginProgress"] | null;
    };
    /** ProviderStatus */
    ProviderStatus: {
      /**
       * Name
       * @enum {string}
       */
      name: "open_meteo" | "tomtom" | "operator_bulletins";
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "not_configured" | "error" | "disabled" | "stale";
      /** Last Poll At */
      last_poll_at?: string | null;
      /** Last Successful Poll At */
      last_successful_poll_at?: string | null;
      /**
       * Consecutive Errors
       * @default 0
       */
      consecutive_errors: number;
      /** Error Message */
      error_message?: string | null;
      /**
       * Mode
       * @enum {string}
       */
      mode: "demo" | "live";
    };
    /** Reason */
    Reason: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | "NODE_HANDLING"
        | "EVENT_HANDLING_DELAY"
        | "WAIT_DEPARTURE"
        | "MISSED_CUTOFF"
        | "LANE_TRAVEL"
        | "EVENT_TRAVEL_DELAY"
        | "CALENDAR_PAUSE";
      /** Minutes */
      minutes: number;
      /** Description */
      description: string;
      /** Event Ids */
      event_ids?: string[];
    };
    /** RefreshIntegrations */
    RefreshIntegrations: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
    };
    /** RefreshResult */
    RefreshResult: {
      snapshot: components["schemas"]["Snapshot"];
      /** Integrations Revision */
      integrations_revision: number;
      /** Refreshed At */
      refreshed_at: string;
      /** Observations Created */
      observations_created: number;
      /** Events Proposed */
      events_proposed: number;
    };
    /** ResetRequest */
    ResetRequest: {
      /**
       * Confirm
       * @constant
       */
      confirm: "RESET_DEMO";
    };
    /** ReviewEvidence */
    ReviewEvidence: {
      reviewed_snapshot: components["schemas"]["Snapshot"];
      selected_itinerary: components["schemas"]["Route"];
      selected_projection?: components["schemas"]["Route"] | null;
      proposed_itinerary?: components["schemas"]["Route"] | null;
      network_snapshot: components["schemas"]["Network"];
      /** Applied Event Versions */
      applied_event_versions?: {
        [key: string]: unknown;
      }[];
      /** Observation Ids */
      observation_ids?: string[];
    };
    /** ReviseEvent */
    ReviseEvent: {
      /** Mutation Id */
      mutation_id: string;
      expected_snapshot: components["schemas"]["Snapshot"];
      /** Expected Version */
      expected_version: number;
      event: components["schemas"]["EventInput"];
    };
    /** Route */
    Route: {
      /** Id */
      id: string;
      /** Lane Ids */
      lane_ids: string[];
      /** Departure Times */
      departure_times: string[];
      /** Arrival At */
      arrival_at: string;
      /** Total Minutes */
      total_minutes: number;
      /** Transfer Count */
      transfer_count: number;
      /** Segments */
      segments: components["schemas"]["Segment"][];
      /** Explanation */
      explanation?: string[];
    };
    /** SearchRequest */
    SearchRequest: {
      /** Origin Id */
      origin_id: string;
      /** Destination Id */
      destination_id: string;
      /** Ready At */
      ready_at: string;
      /** Service Profile Id */
      service_profile_id: string;
      /**
       * Max Results
       * @default 3
       */
      max_results: number;
      /** Arrival Deadline */
      arrival_deadline?: string | null;
    };
    /** SearchResponse */
    SearchResponse: {
      snapshot: components["schemas"]["Snapshot"];
      /** Search Id */
      search_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: "feasible" | "no_feasible_route";
      /** Routes */
      routes?: components["schemas"]["Route"][];
      /** Diagnostics */
      diagnostics?: components["schemas"]["Diagnostic"][];
    };
    /** Segment */
    Segment: {
      /** Segment Index */
      segment_index: number;
      /**
       * Type
       * @enum {string}
       */
      type: "handle" | "travel" | "wait";
      /** Node Id */
      node_id?: string | null;
      /** Lane Id */
      lane_id?: string | null;
      /** Start At */
      start_at: string;
      /** End At */
      end_at: string;
      /** Duration Minutes */
      duration_minutes: number;
      /** Reasons */
      reasons?: components["schemas"]["Reason"][];
    };
    /** ServiceProfile */
    ServiceProfile: {
      /** Id */
      id: string;
      /** Allowed Modes */
      allowed_modes: ("road" | "air")[];
      /** Max Lanes */
      max_lanes: number;
      /**
       * Scope
       * @constant
       */
      scope: "branch_to_branch";
    };
    /** Snapshot */
    Snapshot: {
      /** Dataset Id */
      dataset_id: string;
      /** Schedule Revision */
      schedule_revision: number;
      /** Event Revision */
      event_revision: number;
      /** Clock Revision */
      clock_revision: number;
    };
    /** SourceSummary */
    SourceSummary: {
      /** Filename */
      filename: string;
      /** Rows */
      rows?: number | null;
      /** Date From */
      date_from?: string | null;
      /** Date To */
      date_to?: string | null;
      /** Issues */
      issues?: string[];
      /** Sha256 */
      sha256?: string | null;
    };
    /** State */
    State: {
      /**
       * Api Version
       * @default 2.0.0
       */
      api_version: string;
      snapshot: components["schemas"]["Snapshot"];
      /** Simulation Clock */
      simulation_clock: string;
      /** Demo Mode */
      demo_mode: boolean;
      /**
       * Mode
       * @enum {string}
       */
      mode: "demo" | "live";
      /**
       * Plans Revision
       * @default 0
       */
      plans_revision: number;
      /**
       * Integrations Revision
       * @default 0
       */
      integrations_revision: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  get_state_api_state_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
    };
  };
  get_network_api_network_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Network"];
        };
      };
    };
  };
  get_data_summary_api_data_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataSummary"];
        };
      };
    };
  };
  post_search_api_routes_search_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_lane_api_lanes__lane_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lane_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LaneUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LaneMutationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_node_api_nodes__node_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NodeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodeMutationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_events_api_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventList"];
        };
      };
    };
  };
  post_event_api_events_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEvent"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventMutationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_event_revision_api_events__event_id__revisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviseEvent"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventMutationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_plans_api_plans_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanList"];
        };
      };
    };
  };
  post_plan_api_plans_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePlan"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_plan_view_api_plans__plan_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_decisions_api_plans__plan_id__decisions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_decision_api_plans__plan_id__decisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        plan_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecisionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_preset_api_demo_presets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyPreset"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventMutationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_clock_api_demo_clock_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdvanceClock"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_reset_api_demo_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_map_geometry_api_map_geometry_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MapGeometry"];
        };
      };
    };
  };
  get_integrations_api_integrations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Integrations"];
        };
      };
    };
  };
  get_observations_api_integrations_observations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObservationList"];
        };
      };
    };
  };
  post_integrations_refresh_api_integrations_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshIntegrations"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefreshResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_404_catchall_api__path__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_404_catchall_api__path__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_404_catchall_api__path__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_404_catchall_api__path__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_404_catchall_api__path__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
