import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowRightLeft, MapPin, Route, ShieldCheck, Loader2, Save } from "lucide-react";
import { api } from "../api/client";
import type { NetNode, RouteResp, Operations } from "../api/types";
import { RouteCompare } from "../components/RouteCompare";
import { ScenarioStudio } from "../components/ScenarioStudio";
import { localInput } from "../lib";
export function Planner({nodes,revision,onChange,onReview}:{nodes:NetNode[];revision:number;onChange:()=>void;onReview:()=>void}){
 const [origin,setOrigin]=useState("R16"),[dest,setDest]=useState("R21");
 const [depart,setDepart]=useState(()=>localInput(new Date())),[deadline,setDeadline]=useState(()=>localInput(new Date(Date.now()+3*86400000)));
 const [weight,setWeight]=useState("12000"),[value,setValue]=useState("180000");
 const [resp,setResp]=useState<RouteResp|null>(null),[ops,setOps]=useState<Operations|null>(null);
 const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[err,setErr]=useState(""),[message,setMessage]=useState("");
 const [selected,setSelected]=useState(0);
 const [optimization,setOptimization]=useState("fastest");
 const [truck,setTruck]=useState({height_m:4,width_m:2.55,length_m:16.5,gross_weight_kg:40000});
 const requestId=useRef(0);const lastBody=useRef<Parameters<typeof api.route>[0]|null>(null);
 const body=()=>({origin,destination:dest,depart_at:new Date(depart).toISOString(),required_delivery:deadline?new Date(deadline).toISOString():undefined,weight_kg:Number(weight),value_eur:Number(value),optimization,truck});
 async function go(automatic=false){const id=++requestId.current;setLoading(true);setErr("");if(!automatic)setMessage("");const selectedPath=resp?.options[selected]?.path.join("-");try{const b=body();const r=await api.route(b);if(id===requestId.current){setResp(r);setSelected(automatic?Math.max(0,r.options.findIndex(o=>o.path.join("-")===selectedPath)):0);lastBody.current=b}}catch(e){if(id===requestId.current)setErr(String(e))}finally{if(id===requestId.current)setLoading(false)}}
 useEffect(()=>{let active=true;api.operations().then(r=>{if(active)setOps(r)}).catch(e=>{if(active)setErr(String(e))});return()=>{active=false}},[revision]);
 useEffect(()=>{if(resp&&resp.revision!==revision) void go()},[revision]);
 async function scenarioChanged(){const o=await api.operations();setOps(o);onChange();if(!resp)await go()}
 async function save(recommended=false){setSaving(true);setErr("");try{const b=lastBody.current;if(!b)throw Error("Calculate a route first");const ship=await api.createShipment({...b,planned_departure:b.depart_at,selected_path:resp?.options[recommended?0:selected]?.path});setMessage(`${ship.id} saved. Review and approve its route in the control room.`);onChange()}catch(e){setErr(String(e))}finally{setSaving(false)}}
 function weekendDemo(){setDepart("2026-09-19T08:00");setDeadline("2026-09-22T18:00");setOrigin("R16");setDest("R21");setResp(null);setMessage("Saturday demo loaded. Calculate routes to see any intermediate-hub Weekend Hold.")}
 const dirty=resp&&JSON.stringify(lastBody.current)!==JSON.stringify((()=>{try{return body()}catch{return null}})());
 const refreshLatest=useRef(()=>{});refreshLatest.current=()=>{if(resp&&!dirty&&!loading&&!saving&&!document.hidden)void go(true)};
 useEffect(()=>{const timer=setInterval(()=>refreshLatest.current(),120000);return()=>clearInterval(timer)},[]);
 return <>
 <section className="planner-hero"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> INTELLIGENT TRANSIT PLANNING</span><h1>A changing world.<br/><span>A clearer arrival.</span></h1><p>Real road routes. Explainable ETAs. Every decision,<br className="desktop-break"/> with your operations team in control.</p><div className="hero-tags"><span><Route size={14}/> {nodes.length} facilities</span><span><ShieldCheck size={14}/> Human oversight</span><span>CSV + road routing</span></div></div><div className="hero-route" aria-hidden="true"><div className="hero-route-top"><span>THE JOURNEY, EXPLAINED</span><span>01 → 03</span></div><div className="route-diagram"><i/><span className="dash"/><i/><span className="dash"/><i/></div><div className="route-labels"><span>Origin</span><span>Smart transfer</span><span>Delivery</span></div><div className="hero-route-bottom"><ShieldCheck size={18}/><span>Adapt the plan.<br/><b>Keep the promise.</b></span><ArrowUpRight size={28}/></div></div></section>
 <section className="card planning-card"><div className="card__h"><div><span className="eyebrow">START A JOURNEY</span><h2>Where are we heading?</h2></div><button className="linkbtn" onClick={weekendDemo}>Load Saturday demo ↗</button></div><form onSubmit={e=>{e.preventDefault();void go()}}><div className="plan-fields"><label>Origin<select aria-label="Origin" value={origin} onChange={e=>setOrigin(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><button type="button" className="swap-button" aria-label="Swap origin and destination" onClick={()=>{setOrigin(dest);setDest(origin)}}><ArrowRightLeft size={16}/></button><label>Destination<select aria-label="Destination" value={dest} onChange={e=>setDest(e.target.value)}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Departure · device local time<input required aria-label="Departure" type="datetime-local" value={depart} onChange={e=>setDepart(e.target.value)}/></label><button className="btn btn--mint" disabled={loading||!nodes.length||origin===dest}>{loading?<Loader2 className="spin" size={17}/>:<ArrowUpRight size={17}/>} {loading?"Calculating…":"Find best routes"}</button></div><div className="plan-secondary"><label>Weight · kg<input aria-label="Weight kg" required type="number" min="1" max="23800" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label>Shipment value · €<input aria-label="Shipment value" type="number" min="0" value={value} onChange={e=>setValue(e.target.value)}/></label><label>Deliver by · device local time<input aria-label="Deliver by" type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label>Optimize for<select aria-label="Optimization goal" value={optimization} onChange={e=>setOptimization(e.target.value)}><option value="fastest">Fastest arrival</option><option value="cost">Lowest cost within deadline</option><option value="balanced">Balanced · €50 per transit hour</option></select></label></div><details className="truck-settings"><summary>Truck profile & routing assumptions</summary><div className="truck-fields">{([ ["height_m","Height (m)"],["width_m","Width (m)"],["length_m","Length (m)"],["gross_weight_kg","Gross vehicle weight (kg)"] ] as const).map(([key,label])=><label key={key}>{label}<input required type="number" min="0.1" step="any" value={truck[key]} onChange={e=>setTruck({...truck,[key]:Number(e.target.value)})}/></label>)}</div><p>Defaults are assumptions. Gross weight includes cargo. TomTom uses this profile when configured; OSRM fallback is not truck-certified. Balanced ranking values transit time at €50/hour; it is not an additional billed cost.</p></details></form></section>
 {err&&<div role="alert" className="notice notice--warn">{err}</div>}{message&&<div role="status" className="notice notice--info">{message}<button className="linkbtn" onClick={onReview}>Open control room ↗</button></div>}
 <ScenarioStudio nodes={nodes} origin={origin} destination={dest} start={(()=>{try{return new Date(depart).toISOString()}catch{return new Date().toISOString()}})()} ops={ops} onChange={scenarioChanged}/>
 {resp?<section className={`card results-card ${loading?"is-updating":""}`}>{dirty&&<div className="notice notice--warn">Inputs changed. Calculate again to update these results.</div>}<RouteCompare nodes={nodes} options={resp.options} savings={resp.savings} selected={selected} onSelect={setSelected} onRefresh={()=>{if(!loading)void go(true)}}/><div className="results-actions"><span><ShieldCheck size={16}/> ETAs refresh every 2 minutes while this page is active. Human approval before dispatch.</span><button className="btn btn--ghost" onClick={onReview}>Open control room</button><button className="btn btn--ghost" disabled={saving||loading||!!dirty||resp.revision!==revision} onClick={()=>save(true)}>Save recommended</button><button className="btn" disabled={saving||loading||!!dirty||resp.revision!==revision} onClick={()=>save(false)}><Save size={15}/>{saving?"Saving…":"Save plan for review"}</button></div></section>:<div className="planner-empty"><MapPin size={26}/><h3>Your next delivery promise starts here.</h3><p>Choose a route to compare road geometry, arrival times and operational trade-offs.</p></div>}
 </>
}
